//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_biblioteczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class GodzinyPracy
    {
        public System.DateTime data { get; set; }
        public int pracownik_id { get; set; }
        public int pracownik_id2 { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Pracownicy Pracownicy1 { get; set; }
    }
}
