//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_biblioteczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ksiazki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ksiazki()
        {
            this.Wypozyczenia = new HashSet<Wypozyczenia>();
            this.Zamowienia = new HashSet<Zamowienia>();
        }
    
        public int ksiazka_id { get; set; }
        public string tytul { get; set; }
        public string tytul2 { get; set; }
        public int rok_wydania { get; set; }
        public int autor_id { get; set; }
        public string wydawnictwo { get; set; }
        public int kraj_id { get; set; }
        public string jezyk { get; set; }
        public int numer_wydania { get; set; }
        public int stawka { get; set; }
    
        public virtual Autorzy Autorzy { get; set; }
        public virtual Kraje Kraje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia> Wypozyczenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienia> Zamowienia { get; set; }
    }
}
