//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_biblioteczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loginy
    {
        public int nr_karty { get; set; }
        public string haslo { get; set; }
    
        public virtual Uzytkownicy Uzytkownicy { get; set; }
    }
}
