//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_biblioteczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracownicyDetails
    {
        public int pracownik_id { get; set; }
        public string ulica { get; set; }
        public string miasto { get; set; }
        public string kod_poczt { get; set; }
        public int telefon { get; set; }
        public string adres_mail { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
